[
  "Мне нравится это видео",
  "Мне нравится эта вещь",
  "Я хотел бы выпить чашку кофе",
  "Мне нравится этот плейлист",
  "Я хотел бы сделать это",
  "Я хотел бы посетить это место",
  "Я хотел бы чашку кофе",
  "Я хотел бы стать бизнесменом",
  "Она хотела бы стать учительницей",
  "Ему нравится это платье",
  "Я вижу, тебе реально нравится английский",
  "Моему другу нравится этот отель",
  "Мне нравится английский",
  "Мне действительно нравится этот плейлист",
  "Мне нравится этот канал",
  "Ей нравится это место",
  "Тебе нравится это",
  "Ей нравится это",
  "Я вижу, ему это реально нравится",
  "Мне действително нравится этот канал",
  "Я хотел бы знать английский очень хорошо",
  "Им нравится это",
  "Мне нравится это",
  "Я хотел бы выпить чашку чая",
  "Я знаю, им это нравится",
  "Мне нравится этот метод",
  "Нам нравится это",
  "Я хотел бы чашку чая",
  "Мне так же нравится этот канал",
  "Мне нравится этот канал так же",
  "Мне реально нравится это место",
  "Мне реально это нравится",
  "Он хотел бы стать врачом",
  "Мне нравятся твои уроки",
  "Я хотел бы стать бизнесменом",
  "Мне реально нравятя эти уроки",
  "Я хотел бы стать менеджером",
  "Мне нравится эта идея",
  "Я хотел бы поехать за границу",
  "Она хотела бы поехать в другое место",
],
[
  "I like this video",
  "I like this thing",
  "I`d like to drink a cup of coffee",
  "I like this playlist",
  "I`d like to do it",
  "I`d like to visit this place",
  "I`d like a cup of coffee",
  "I`d like to become a businessman",
  "She`d like to become a teacher",
  "He likes this dress",
  "I see you really like English",
  "My friend likes this hotel",
  "I like English",
  "I really like this playlist",
  "I like this shannel",
  "She likes this place",
  "You like it",
  "She likes it",
  "I see he really likes it",
  "I really like this shannel",
  "I`d like to know English very well",
  "They like it",
  "I like it",
  "I`d like to drink a cup of tea",
  "I know they like it",
  "I like this method",
  "We like it",
  "I`d like a cup of tea",
  "I also like this shannel",
  "I like this cshannel, too",
  "I really like this place",
  "I really like it",
  "He`d like to become a doctor",
  "I like your lessons",
  "I`d like to become a businessman",
  "I really like these lessons",
  "I`d like to become a manager",
  "I like this idea",
  "I`d like to go abroad",
  "She`d like to go to another place",
]